### ISSUE TITLE
Kétoldalas nyomtatás

### ISSUE THREAD

**Issue by ehog90** [shdnx/ELTE-LaTeX-Thesis-Base#1]
\documentclass[twoside, a4paper, 12pt]{article}
helyett
\documentclass[oneside, a4paper, 12pt]{article}
kell. lásd:

http://www.inf.elte.hu/karunkrol/szervezet/dekanihivatal/to/szigorlat_nagyprogram_zarovizsga/Documents/progmat_szakdoli.pdf

**Comment by shdnx** [comment]
Kedves ehog90,

Amit linkeltél, az a Programtervező Matematika szakdolgozatára vonatkozó követelmények, amely szak már (tudtommal) nem indul.
A programtervező informatikus BSc szakdolgozati követelmények: http://www.inf.elte.hu/karunkrol/szervezet/dekanihivatal/to/szigorlat_nagyprogram_zarovizsga/Documents/PTI_BSc_szakdoli_uj.pdf
Ez nem tartalmazza az 1 oldalas korlátozást.
Én tavaly, amikor lediplomáztam, 2 oldalasan nyomtattam, és elfogadták minden probléma nélkül.
